APP:
  ENVIRONMENT: test
  DEBUG: True
  API_KEY:  'dd764c65e8685d30f05dddbe0f2f9e04'
  BASE_URL: 'https://api.themoviedb.org/3/'

DATABASE:
  DATABASE_URL: 'postgresql+psycopg2://postgres:postgres@localhost:5432/imdb'
  USERNAME: xiaoxu
  PASSWORD: xiaoxu
  HOST: 127.0.0.1
  PORT: 5432
  DB: xiaoxu_database

TMDB_REQUEST_TYPES:
  movie:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api:themoviedb.org/3/movie/{id}?api_key={api_key}'
  person:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/'
  collection:
    MAX_REQUEST_KEY: 20000
    URL: 'https://api.themoviedb.org/3/'
  company:
    MAX_REQUEST_KEY: 10000
    URL: 'https://api.themoviedb.org/3/'
  credit:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/movie/{id}/credits?api_key={api_key}'
  keyword:
    MAX_REQUEST_KEY: 10000
    URL: 'https://api.themoviedb.org/3/'
  people:
    MAX_REQUEST_KEY: 1000000
    URL: 'https://api.themoviedb.org/3/'

